### ISSUE TITLE
Issues with seeding

### ISSUE THREAD

**Issue by anselmdk** [stevie-mayhew/silverstripe-redux-example#1]
I'm having a few issues seeding the data:

**1.**

```
[InvalidArgumentException]                              
 text() can only generate text of at least 5 characters 
```

I managed to temporarily fix that by hardcoding `$maxNbChars = 10;` in the `text` method in `Faker\Provider\Lorem`.

**2.**

`PHP Fatal error:  Class 'LittleGiant\SilverStripeSeeder\Tests\TestProvider'`

I'm not sure how to fix this.

**Comment by stevie-mayhew** [comment]
@anselmdk sorry about that - I've updated the code so it should now work :smile:

**Comment by anselmdk** [comment]
Great, thanks.
It's a great example by the way! I love the way you're integrating Webpack.

**Comment by stevie-mayhew** [comment]
@anselmdk thanks :) Some of it is a wee bit against how it should be (the setter for example) but I thought it would be handy for others :)

**Comment by anselmdk** [comment]
It certainly is.
